FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1
ENV TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD=true
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    ffmpeg \
    git \
    libgl1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN python3 -m pip install --upgrade pip


COPY requirements.txt .
RUN python3 -m pip install --no-cache-dir -r requirements.txt

COPY preload_models.py .
RUN python3 preload_models.py

COPY . .

RUN pip freeze

ENV PORT=8080


CMD exec functions-framework --target=createShortsJob --source=main.py --port=$PORT